Run interval from config
RedHatQE/ci-jobs-trigger pull request #100
Opened 2024-04-12 20:00 UTC by myakove

2024-04-12 20:37 UTC, myakove commented
`tox` fixed in https://github.com/RedHatQE/ci-jobs-trigger/pull/98

2024-04-14 09:54 UTC, rnetser requested changes

2024-04-14 09:54 UTC, rnetser commented on config-examples/zstream-trigger-config.example.yaml
> +run_interval: 24h # can be s/m/h
readme please

2024-04-14 10:43 UTC, rnetser approved these changes

2024-04-14 10:43 UTC, myakove commented
/verified

2024-04-14 10:43 UTC, merged

2024-04-14 10:45 UTC, redhat-qe-bot1 commented
New container for quay.io/redhat_msi/ci-jobs-trigger:latest published