add jenkins iib parameter support
RedHatQE/ci-jobs-trigger pull request #38
Opened 2024-03-06 13:21 UTC by rnetser

2024-03-06 14:53 UTC, rnetser commented
/verified

2024-03-06 15:10 UTC, myakove requested changes

2024-03-06 15:10 UTC, myakove commented on ci_jobs_trigger/libs/jenkins/utils/general.py
> +    return wait_for_job_in_jenkins(api=api, job=job, last_build_number=last_build_number, logger=logger)
```suggestion
    return wait_for_job_started_in_jenkins(api=api, job=job, last_build_number=last_build_number, logger=logger)
```

2024-03-06 15:10 UTC, myakove commented on ci_jobs_trigger/libs/jenkins/utils/general.py
> +            job_params[param["defaultParameterValue"]["name"]] = param["defaultParameterValue"]["value"]
`param["defaultParameterValue"]["name"]` can be `param["name"]` ?

2024-03-06 15:37 UTC, myakove submitted a review, later dismissed

2024-03-06 15:37 UTC, rnetser commented
/verified

2024-03-06 15:47 UTC, rnetser commented
/verified

2024-03-07 09:03 UTC, myakove approved these changes

2024-03-07 09:03 UTC, merged

2024-03-07 09:04 UTC, redhat-qe-bot2 commented
New container for quay.io/redhat_msi/ci-jobs-trigger:latest published