WIP: Add openshift ci job re trigger
RedHatQE/ci-jobs-trigger pull request #5
Opened 2024-02-21 20:05 UTC by rnetser

2024-02-21 20:05 UTC, redhat-qe-bot1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest build-container`: Retest build-container

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-02-22 07:22 UTC, myakove requested changes

2024-02-22 07:22 UTC, myakove commented on ci_jobs_trigger/app.py
> +from ci_jobs_trigger.libs.openshift_ci_re_trigger.openshift_ci_re_trigger import (
if you put `openshift_ci_re_trigger` code under folder please do the same for `zstream_trigger`

2024-02-22 07:22 UTC, myakove commented on ci_jobs_trigger/app.py
> +        job_triggering = JobTriggering(hook_data=request.json, flask_logger=APP.logger)
let's keep it unified, please rename `flask_logger` to `logger`

2024-02-22 07:22 UTC, myakove commented on ci_jobs_trigger/libs/openshift_ci_re_trigger/openshift_ci_re_trigger.py
> +            prow_job_id = self.trigger_job()
we need to rename either `trigger_job()` or `self.trigger_job()`, preferred to rename the self one

2024-02-22 07:22 UTC, myakove commented on ci_jobs_trigger/libs/openshift_ci_re_trigger/openshift_ci_re_trigger.py
> +        self.config = get_config(os_environ=OPENSHIFT_CI_RE_TRIGGER_CONFIG_OS_ENV_STR)
need to exit if not config.

2024-02-22 07:24 UTC, myakove commented
`tests` folder should move under `ci_jobs_trigger` folder.

2024-02-22 11:14 UTC, rnetser commented
/wip cancel

2024-02-22 13:03 UTC, myakove approved these changes

2024-02-22 13:04 UTC, rnetser commented
/verified

2024-02-22 13:04 UTC, merged

2024-02-22 13:04 UTC, redhat-qe-bot1 commented
New container for quay.io/redhat_msi/ci-jobs-trigger:latest published